/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as TaskManagementRouteImport } from './routes/task-management'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeavesRouteImport } from './routes/leaves'
import { Route as HierarchyRouteImport } from './routes/hierarchy'
import { Route as EmployeesRouteImport } from './routes/employees'
import { Route as EmployeeReportRouteImport } from './routes/employee-report'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AccessControlRouteImport } from './routes/access-control'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WmsIndexRouteImport } from './routes/wms/index'
import { Route as HiringIndexRouteImport } from './routes/hiring/index'
import { Route as WmsVendorsRouteImport } from './routes/wms/vendors'
import { Route as WmsStockTransferRouteImport } from './routes/wms/stock-transfer'
import { Route as WmsStockOutRouteImport } from './routes/wms/stock-out'
import { Route as WmsStockInRouteImport } from './routes/wms/stock-in'
import { Route as WmsSettingsRouteImport } from './routes/wms/settings'
import { Route as WmsSalesInvoicesRouteImport } from './routes/wms/sales-invoices'
import { Route as WmsReportsRouteImport } from './routes/wms/reports'
import { Route as WmsProductsRouteImport } from './routes/wms/products'
import { Route as WmsLocationsRouteImport } from './routes/wms/locations'
import { Route as WmsInventoryRouteImport } from './routes/wms/inventory'
import { Route as WmsCustomersRouteImport } from './routes/wms/customers'
import { Route as WmsCategoriesRouteImport } from './routes/wms/categories'
import { Route as Wms3dViewRouteImport } from './routes/wms/3d-view'
import { Route as PublicHiringExamRouteImport } from './routes/public/hiring-exam'
import { Route as ProfileEmployeeIdRouteImport } from './routes/profile.$employeeId'
import { Route as HiringSettingsRouteImport } from './routes/hiring/settings'
import { Route as HiringReportsRouteImport } from './routes/hiring/reports'
import { Route as HiringQuestionBankRouteImport } from './routes/hiring/question-bank'
import { Route as HiringPipelineRouteImport } from './routes/hiring/pipeline'
import { Route as HiringOnboardingRouteImport } from './routes/hiring/onboarding'
import { Route as HiringOffersRouteImport } from './routes/hiring/offers'
import { Route as HiringJoiningRouteImport } from './routes/hiring/joining'
import { Route as HiringJobsRouteImport } from './routes/hiring/jobs'
import { Route as HiringInterviewsRouteImport } from './routes/hiring/interviews'
import { Route as HiringExamCenterRouteImport } from './routes/hiring/exam-center'
import { Route as HiringDashboardRouteImport } from './routes/hiring/dashboard'
import { Route as HiringCandidatesRouteImport } from './routes/hiring/candidates'
import { Route as HiringAnswerSheetsRouteImport } from './routes/hiring/answer-sheets'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskManagementRoute = TaskManagementRouteImport.update({
  id: '/task-management',
  path: '/task-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeavesRoute = LeavesRouteImport.update({
  id: '/leaves',
  path: '/leaves',
  getParentRoute: () => rootRouteImport,
} as any)
const HierarchyRoute = HierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeesRoute = EmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeReportRoute = EmployeeReportRouteImport.update({
  id: '/employee-report',
  path: '/employee-report',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessControlRoute = AccessControlRouteImport.update({
  id: '/access-control',
  path: '/access-control',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsIndexRoute = WmsIndexRouteImport.update({
  id: '/wms/',
  path: '/wms/',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringIndexRoute = HiringIndexRouteImport.update({
  id: '/hiring/',
  path: '/hiring/',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsVendorsRoute = WmsVendorsRouteImport.update({
  id: '/wms/vendors',
  path: '/wms/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsStockTransferRoute = WmsStockTransferRouteImport.update({
  id: '/wms/stock-transfer',
  path: '/wms/stock-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsStockOutRoute = WmsStockOutRouteImport.update({
  id: '/wms/stock-out',
  path: '/wms/stock-out',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsStockInRoute = WmsStockInRouteImport.update({
  id: '/wms/stock-in',
  path: '/wms/stock-in',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsSettingsRoute = WmsSettingsRouteImport.update({
  id: '/wms/settings',
  path: '/wms/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsSalesInvoicesRoute = WmsSalesInvoicesRouteImport.update({
  id: '/wms/sales-invoices',
  path: '/wms/sales-invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsReportsRoute = WmsReportsRouteImport.update({
  id: '/wms/reports',
  path: '/wms/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsProductsRoute = WmsProductsRouteImport.update({
  id: '/wms/products',
  path: '/wms/products',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsLocationsRoute = WmsLocationsRouteImport.update({
  id: '/wms/locations',
  path: '/wms/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsInventoryRoute = WmsInventoryRouteImport.update({
  id: '/wms/inventory',
  path: '/wms/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsCustomersRoute = WmsCustomersRouteImport.update({
  id: '/wms/customers',
  path: '/wms/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const WmsCategoriesRoute = WmsCategoriesRouteImport.update({
  id: '/wms/categories',
  path: '/wms/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const Wms3dViewRoute = Wms3dViewRouteImport.update({
  id: '/wms/3d-view',
  path: '/wms/3d-view',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicHiringExamRoute = PublicHiringExamRouteImport.update({
  id: '/public/hiring-exam',
  path: '/public/hiring-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEmployeeIdRoute = ProfileEmployeeIdRouteImport.update({
  id: '/profile/$employeeId',
  path: '/profile/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringSettingsRoute = HiringSettingsRouteImport.update({
  id: '/hiring/settings',
  path: '/hiring/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringReportsRoute = HiringReportsRouteImport.update({
  id: '/hiring/reports',
  path: '/hiring/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringQuestionBankRoute = HiringQuestionBankRouteImport.update({
  id: '/hiring/question-bank',
  path: '/hiring/question-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringPipelineRoute = HiringPipelineRouteImport.update({
  id: '/hiring/pipeline',
  path: '/hiring/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringOnboardingRoute = HiringOnboardingRouteImport.update({
  id: '/hiring/onboarding',
  path: '/hiring/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringOffersRoute = HiringOffersRouteImport.update({
  id: '/hiring/offers',
  path: '/hiring/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringJoiningRoute = HiringJoiningRouteImport.update({
  id: '/hiring/joining',
  path: '/hiring/joining',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringJobsRoute = HiringJobsRouteImport.update({
  id: '/hiring/jobs',
  path: '/hiring/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringInterviewsRoute = HiringInterviewsRouteImport.update({
  id: '/hiring/interviews',
  path: '/hiring/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringExamCenterRoute = HiringExamCenterRouteImport.update({
  id: '/hiring/exam-center',
  path: '/hiring/exam-center',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringDashboardRoute = HiringDashboardRouteImport.update({
  id: '/hiring/dashboard',
  path: '/hiring/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringCandidatesRoute = HiringCandidatesRouteImport.update({
  id: '/hiring/candidates',
  path: '/hiring/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const HiringAnswerSheetsRoute = HiringAnswerSheetsRouteImport.update({
  id: '/hiring/answer-sheets',
  path: '/hiring/answer-sheets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/employee-report': typeof EmployeeReportRoute
  '/employees': typeof EmployeesRoute
  '/hierarchy': typeof HierarchyRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/task-management': typeof TaskManagementRoute
  '/welcome': typeof WelcomeRoute
  '/hiring/answer-sheets': typeof HiringAnswerSheetsRoute
  '/hiring/candidates': typeof HiringCandidatesRoute
  '/hiring/dashboard': typeof HiringDashboardRoute
  '/hiring/exam-center': typeof HiringExamCenterRoute
  '/hiring/interviews': typeof HiringInterviewsRoute
  '/hiring/jobs': typeof HiringJobsRoute
  '/hiring/joining': typeof HiringJoiningRoute
  '/hiring/offers': typeof HiringOffersRoute
  '/hiring/onboarding': typeof HiringOnboardingRoute
  '/hiring/pipeline': typeof HiringPipelineRoute
  '/hiring/question-bank': typeof HiringQuestionBankRoute
  '/hiring/reports': typeof HiringReportsRoute
  '/hiring/settings': typeof HiringSettingsRoute
  '/profile/$employeeId': typeof ProfileEmployeeIdRoute
  '/public/hiring-exam': typeof PublicHiringExamRoute
  '/wms/3d-view': typeof Wms3dViewRoute
  '/wms/categories': typeof WmsCategoriesRoute
  '/wms/customers': typeof WmsCustomersRoute
  '/wms/inventory': typeof WmsInventoryRoute
  '/wms/locations': typeof WmsLocationsRoute
  '/wms/products': typeof WmsProductsRoute
  '/wms/reports': typeof WmsReportsRoute
  '/wms/sales-invoices': typeof WmsSalesInvoicesRoute
  '/wms/settings': typeof WmsSettingsRoute
  '/wms/stock-in': typeof WmsStockInRoute
  '/wms/stock-out': typeof WmsStockOutRoute
  '/wms/stock-transfer': typeof WmsStockTransferRoute
  '/wms/vendors': typeof WmsVendorsRoute
  '/hiring/': typeof HiringIndexRoute
  '/wms/': typeof WmsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/employee-report': typeof EmployeeReportRoute
  '/employees': typeof EmployeesRoute
  '/hierarchy': typeof HierarchyRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/task-management': typeof TaskManagementRoute
  '/welcome': typeof WelcomeRoute
  '/hiring/answer-sheets': typeof HiringAnswerSheetsRoute
  '/hiring/candidates': typeof HiringCandidatesRoute
  '/hiring/dashboard': typeof HiringDashboardRoute
  '/hiring/exam-center': typeof HiringExamCenterRoute
  '/hiring/interviews': typeof HiringInterviewsRoute
  '/hiring/jobs': typeof HiringJobsRoute
  '/hiring/joining': typeof HiringJoiningRoute
  '/hiring/offers': typeof HiringOffersRoute
  '/hiring/onboarding': typeof HiringOnboardingRoute
  '/hiring/pipeline': typeof HiringPipelineRoute
  '/hiring/question-bank': typeof HiringQuestionBankRoute
  '/hiring/reports': typeof HiringReportsRoute
  '/hiring/settings': typeof HiringSettingsRoute
  '/profile/$employeeId': typeof ProfileEmployeeIdRoute
  '/public/hiring-exam': typeof PublicHiringExamRoute
  '/wms/3d-view': typeof Wms3dViewRoute
  '/wms/categories': typeof WmsCategoriesRoute
  '/wms/customers': typeof WmsCustomersRoute
  '/wms/inventory': typeof WmsInventoryRoute
  '/wms/locations': typeof WmsLocationsRoute
  '/wms/products': typeof WmsProductsRoute
  '/wms/reports': typeof WmsReportsRoute
  '/wms/sales-invoices': typeof WmsSalesInvoicesRoute
  '/wms/settings': typeof WmsSettingsRoute
  '/wms/stock-in': typeof WmsStockInRoute
  '/wms/stock-out': typeof WmsStockOutRoute
  '/wms/stock-transfer': typeof WmsStockTransferRoute
  '/wms/vendors': typeof WmsVendorsRoute
  '/hiring': typeof HiringIndexRoute
  '/wms': typeof WmsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/access-control': typeof AccessControlRoute
  '/attendance': typeof AttendanceRoute
  '/dashboard': typeof DashboardRoute
  '/employee-report': typeof EmployeeReportRoute
  '/employees': typeof EmployeesRoute
  '/hierarchy': typeof HierarchyRoute
  '/leaves': typeof LeavesRoute
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/task-management': typeof TaskManagementRoute
  '/welcome': typeof WelcomeRoute
  '/hiring/answer-sheets': typeof HiringAnswerSheetsRoute
  '/hiring/candidates': typeof HiringCandidatesRoute
  '/hiring/dashboard': typeof HiringDashboardRoute
  '/hiring/exam-center': typeof HiringExamCenterRoute
  '/hiring/interviews': typeof HiringInterviewsRoute
  '/hiring/jobs': typeof HiringJobsRoute
  '/hiring/joining': typeof HiringJoiningRoute
  '/hiring/offers': typeof HiringOffersRoute
  '/hiring/onboarding': typeof HiringOnboardingRoute
  '/hiring/pipeline': typeof HiringPipelineRoute
  '/hiring/question-bank': typeof HiringQuestionBankRoute
  '/hiring/reports': typeof HiringReportsRoute
  '/hiring/settings': typeof HiringSettingsRoute
  '/profile/$employeeId': typeof ProfileEmployeeIdRoute
  '/public/hiring-exam': typeof PublicHiringExamRoute
  '/wms/3d-view': typeof Wms3dViewRoute
  '/wms/categories': typeof WmsCategoriesRoute
  '/wms/customers': typeof WmsCustomersRoute
  '/wms/inventory': typeof WmsInventoryRoute
  '/wms/locations': typeof WmsLocationsRoute
  '/wms/products': typeof WmsProductsRoute
  '/wms/reports': typeof WmsReportsRoute
  '/wms/sales-invoices': typeof WmsSalesInvoicesRoute
  '/wms/settings': typeof WmsSettingsRoute
  '/wms/stock-in': typeof WmsStockInRoute
  '/wms/stock-out': typeof WmsStockOutRoute
  '/wms/stock-transfer': typeof WmsStockTransferRoute
  '/wms/vendors': typeof WmsVendorsRoute
  '/hiring/': typeof HiringIndexRoute
  '/wms/': typeof WmsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-control'
    | '/attendance'
    | '/dashboard'
    | '/employee-report'
    | '/employees'
    | '/hierarchy'
    | '/leaves'
    | '/login'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/task-management'
    | '/welcome'
    | '/hiring/answer-sheets'
    | '/hiring/candidates'
    | '/hiring/dashboard'
    | '/hiring/exam-center'
    | '/hiring/interviews'
    | '/hiring/jobs'
    | '/hiring/joining'
    | '/hiring/offers'
    | '/hiring/onboarding'
    | '/hiring/pipeline'
    | '/hiring/question-bank'
    | '/hiring/reports'
    | '/hiring/settings'
    | '/profile/$employeeId'
    | '/public/hiring-exam'
    | '/wms/3d-view'
    | '/wms/categories'
    | '/wms/customers'
    | '/wms/inventory'
    | '/wms/locations'
    | '/wms/products'
    | '/wms/reports'
    | '/wms/sales-invoices'
    | '/wms/settings'
    | '/wms/stock-in'
    | '/wms/stock-out'
    | '/wms/stock-transfer'
    | '/wms/vendors'
    | '/hiring/'
    | '/wms/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-control'
    | '/attendance'
    | '/dashboard'
    | '/employee-report'
    | '/employees'
    | '/hierarchy'
    | '/leaves'
    | '/login'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/task-management'
    | '/welcome'
    | '/hiring/answer-sheets'
    | '/hiring/candidates'
    | '/hiring/dashboard'
    | '/hiring/exam-center'
    | '/hiring/interviews'
    | '/hiring/jobs'
    | '/hiring/joining'
    | '/hiring/offers'
    | '/hiring/onboarding'
    | '/hiring/pipeline'
    | '/hiring/question-bank'
    | '/hiring/reports'
    | '/hiring/settings'
    | '/profile/$employeeId'
    | '/public/hiring-exam'
    | '/wms/3d-view'
    | '/wms/categories'
    | '/wms/customers'
    | '/wms/inventory'
    | '/wms/locations'
    | '/wms/products'
    | '/wms/reports'
    | '/wms/sales-invoices'
    | '/wms/settings'
    | '/wms/stock-in'
    | '/wms/stock-out'
    | '/wms/stock-transfer'
    | '/wms/vendors'
    | '/hiring'
    | '/wms'
  id:
    | '__root__'
    | '/'
    | '/access-control'
    | '/attendance'
    | '/dashboard'
    | '/employee-report'
    | '/employees'
    | '/hierarchy'
    | '/leaves'
    | '/login'
    | '/payroll'
    | '/reports'
    | '/settings'
    | '/task-management'
    | '/welcome'
    | '/hiring/answer-sheets'
    | '/hiring/candidates'
    | '/hiring/dashboard'
    | '/hiring/exam-center'
    | '/hiring/interviews'
    | '/hiring/jobs'
    | '/hiring/joining'
    | '/hiring/offers'
    | '/hiring/onboarding'
    | '/hiring/pipeline'
    | '/hiring/question-bank'
    | '/hiring/reports'
    | '/hiring/settings'
    | '/profile/$employeeId'
    | '/public/hiring-exam'
    | '/wms/3d-view'
    | '/wms/categories'
    | '/wms/customers'
    | '/wms/inventory'
    | '/wms/locations'
    | '/wms/products'
    | '/wms/reports'
    | '/wms/sales-invoices'
    | '/wms/settings'
    | '/wms/stock-in'
    | '/wms/stock-out'
    | '/wms/stock-transfer'
    | '/wms/vendors'
    | '/hiring/'
    | '/wms/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessControlRoute: typeof AccessControlRoute
  AttendanceRoute: typeof AttendanceRoute
  DashboardRoute: typeof DashboardRoute
  EmployeeReportRoute: typeof EmployeeReportRoute
  EmployeesRoute: typeof EmployeesRoute
  HierarchyRoute: typeof HierarchyRoute
  LeavesRoute: typeof LeavesRoute
  LoginRoute: typeof LoginRoute
  PayrollRoute: typeof PayrollRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TaskManagementRoute: typeof TaskManagementRoute
  WelcomeRoute: typeof WelcomeRoute
  HiringAnswerSheetsRoute: typeof HiringAnswerSheetsRoute
  HiringCandidatesRoute: typeof HiringCandidatesRoute
  HiringDashboardRoute: typeof HiringDashboardRoute
  HiringExamCenterRoute: typeof HiringExamCenterRoute
  HiringInterviewsRoute: typeof HiringInterviewsRoute
  HiringJobsRoute: typeof HiringJobsRoute
  HiringJoiningRoute: typeof HiringJoiningRoute
  HiringOffersRoute: typeof HiringOffersRoute
  HiringOnboardingRoute: typeof HiringOnboardingRoute
  HiringPipelineRoute: typeof HiringPipelineRoute
  HiringQuestionBankRoute: typeof HiringQuestionBankRoute
  HiringReportsRoute: typeof HiringReportsRoute
  HiringSettingsRoute: typeof HiringSettingsRoute
  ProfileEmployeeIdRoute: typeof ProfileEmployeeIdRoute
  PublicHiringExamRoute: typeof PublicHiringExamRoute
  Wms3dViewRoute: typeof Wms3dViewRoute
  WmsCategoriesRoute: typeof WmsCategoriesRoute
  WmsCustomersRoute: typeof WmsCustomersRoute
  WmsInventoryRoute: typeof WmsInventoryRoute
  WmsLocationsRoute: typeof WmsLocationsRoute
  WmsProductsRoute: typeof WmsProductsRoute
  WmsReportsRoute: typeof WmsReportsRoute
  WmsSalesInvoicesRoute: typeof WmsSalesInvoicesRoute
  WmsSettingsRoute: typeof WmsSettingsRoute
  WmsStockInRoute: typeof WmsStockInRoute
  WmsStockOutRoute: typeof WmsStockOutRoute
  WmsStockTransferRoute: typeof WmsStockTransferRoute
  WmsVendorsRoute: typeof WmsVendorsRoute
  HiringIndexRoute: typeof HiringIndexRoute
  WmsIndexRoute: typeof WmsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task-management': {
      id: '/task-management'
      path: '/task-management'
      fullPath: '/task-management'
      preLoaderRoute: typeof TaskManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaves': {
      id: '/leaves'
      path: '/leaves'
      fullPath: '/leaves'
      preLoaderRoute: typeof LeavesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hierarchy': {
      id: '/hierarchy'
      path: '/hierarchy'
      fullPath: '/hierarchy'
      preLoaderRoute: typeof HierarchyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employees': {
      id: '/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof EmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-report': {
      id: '/employee-report'
      path: '/employee-report'
      fullPath: '/employee-report'
      preLoaderRoute: typeof EmployeeReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-control': {
      id: '/access-control'
      path: '/access-control'
      fullPath: '/access-control'
      preLoaderRoute: typeof AccessControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/': {
      id: '/wms/'
      path: '/wms'
      fullPath: '/wms/'
      preLoaderRoute: typeof WmsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/': {
      id: '/hiring/'
      path: '/hiring'
      fullPath: '/hiring/'
      preLoaderRoute: typeof HiringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/vendors': {
      id: '/wms/vendors'
      path: '/wms/vendors'
      fullPath: '/wms/vendors'
      preLoaderRoute: typeof WmsVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/stock-transfer': {
      id: '/wms/stock-transfer'
      path: '/wms/stock-transfer'
      fullPath: '/wms/stock-transfer'
      preLoaderRoute: typeof WmsStockTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/stock-out': {
      id: '/wms/stock-out'
      path: '/wms/stock-out'
      fullPath: '/wms/stock-out'
      preLoaderRoute: typeof WmsStockOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/stock-in': {
      id: '/wms/stock-in'
      path: '/wms/stock-in'
      fullPath: '/wms/stock-in'
      preLoaderRoute: typeof WmsStockInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/settings': {
      id: '/wms/settings'
      path: '/wms/settings'
      fullPath: '/wms/settings'
      preLoaderRoute: typeof WmsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/sales-invoices': {
      id: '/wms/sales-invoices'
      path: '/wms/sales-invoices'
      fullPath: '/wms/sales-invoices'
      preLoaderRoute: typeof WmsSalesInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/reports': {
      id: '/wms/reports'
      path: '/wms/reports'
      fullPath: '/wms/reports'
      preLoaderRoute: typeof WmsReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/products': {
      id: '/wms/products'
      path: '/wms/products'
      fullPath: '/wms/products'
      preLoaderRoute: typeof WmsProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/locations': {
      id: '/wms/locations'
      path: '/wms/locations'
      fullPath: '/wms/locations'
      preLoaderRoute: typeof WmsLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/inventory': {
      id: '/wms/inventory'
      path: '/wms/inventory'
      fullPath: '/wms/inventory'
      preLoaderRoute: typeof WmsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/customers': {
      id: '/wms/customers'
      path: '/wms/customers'
      fullPath: '/wms/customers'
      preLoaderRoute: typeof WmsCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/categories': {
      id: '/wms/categories'
      path: '/wms/categories'
      fullPath: '/wms/categories'
      preLoaderRoute: typeof WmsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wms/3d-view': {
      id: '/wms/3d-view'
      path: '/wms/3d-view'
      fullPath: '/wms/3d-view'
      preLoaderRoute: typeof Wms3dViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public/hiring-exam': {
      id: '/public/hiring-exam'
      path: '/public/hiring-exam'
      fullPath: '/public/hiring-exam'
      preLoaderRoute: typeof PublicHiringExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$employeeId': {
      id: '/profile/$employeeId'
      path: '/profile/$employeeId'
      fullPath: '/profile/$employeeId'
      preLoaderRoute: typeof ProfileEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/settings': {
      id: '/hiring/settings'
      path: '/hiring/settings'
      fullPath: '/hiring/settings'
      preLoaderRoute: typeof HiringSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/reports': {
      id: '/hiring/reports'
      path: '/hiring/reports'
      fullPath: '/hiring/reports'
      preLoaderRoute: typeof HiringReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/question-bank': {
      id: '/hiring/question-bank'
      path: '/hiring/question-bank'
      fullPath: '/hiring/question-bank'
      preLoaderRoute: typeof HiringQuestionBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/pipeline': {
      id: '/hiring/pipeline'
      path: '/hiring/pipeline'
      fullPath: '/hiring/pipeline'
      preLoaderRoute: typeof HiringPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/onboarding': {
      id: '/hiring/onboarding'
      path: '/hiring/onboarding'
      fullPath: '/hiring/onboarding'
      preLoaderRoute: typeof HiringOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/offers': {
      id: '/hiring/offers'
      path: '/hiring/offers'
      fullPath: '/hiring/offers'
      preLoaderRoute: typeof HiringOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/joining': {
      id: '/hiring/joining'
      path: '/hiring/joining'
      fullPath: '/hiring/joining'
      preLoaderRoute: typeof HiringJoiningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/jobs': {
      id: '/hiring/jobs'
      path: '/hiring/jobs'
      fullPath: '/hiring/jobs'
      preLoaderRoute: typeof HiringJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/interviews': {
      id: '/hiring/interviews'
      path: '/hiring/interviews'
      fullPath: '/hiring/interviews'
      preLoaderRoute: typeof HiringInterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/exam-center': {
      id: '/hiring/exam-center'
      path: '/hiring/exam-center'
      fullPath: '/hiring/exam-center'
      preLoaderRoute: typeof HiringExamCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/dashboard': {
      id: '/hiring/dashboard'
      path: '/hiring/dashboard'
      fullPath: '/hiring/dashboard'
      preLoaderRoute: typeof HiringDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/candidates': {
      id: '/hiring/candidates'
      path: '/hiring/candidates'
      fullPath: '/hiring/candidates'
      preLoaderRoute: typeof HiringCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hiring/answer-sheets': {
      id: '/hiring/answer-sheets'
      path: '/hiring/answer-sheets'
      fullPath: '/hiring/answer-sheets'
      preLoaderRoute: typeof HiringAnswerSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessControlRoute: AccessControlRoute,
  AttendanceRoute: AttendanceRoute,
  DashboardRoute: DashboardRoute,
  EmployeeReportRoute: EmployeeReportRoute,
  EmployeesRoute: EmployeesRoute,
  HierarchyRoute: HierarchyRoute,
  LeavesRoute: LeavesRoute,
  LoginRoute: LoginRoute,
  PayrollRoute: PayrollRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TaskManagementRoute: TaskManagementRoute,
  WelcomeRoute: WelcomeRoute,
  HiringAnswerSheetsRoute: HiringAnswerSheetsRoute,
  HiringCandidatesRoute: HiringCandidatesRoute,
  HiringDashboardRoute: HiringDashboardRoute,
  HiringExamCenterRoute: HiringExamCenterRoute,
  HiringInterviewsRoute: HiringInterviewsRoute,
  HiringJobsRoute: HiringJobsRoute,
  HiringJoiningRoute: HiringJoiningRoute,
  HiringOffersRoute: HiringOffersRoute,
  HiringOnboardingRoute: HiringOnboardingRoute,
  HiringPipelineRoute: HiringPipelineRoute,
  HiringQuestionBankRoute: HiringQuestionBankRoute,
  HiringReportsRoute: HiringReportsRoute,
  HiringSettingsRoute: HiringSettingsRoute,
  ProfileEmployeeIdRoute: ProfileEmployeeIdRoute,
  PublicHiringExamRoute: PublicHiringExamRoute,
  Wms3dViewRoute: Wms3dViewRoute,
  WmsCategoriesRoute: WmsCategoriesRoute,
  WmsCustomersRoute: WmsCustomersRoute,
  WmsInventoryRoute: WmsInventoryRoute,
  WmsLocationsRoute: WmsLocationsRoute,
  WmsProductsRoute: WmsProductsRoute,
  WmsReportsRoute: WmsReportsRoute,
  WmsSalesInvoicesRoute: WmsSalesInvoicesRoute,
  WmsSettingsRoute: WmsSettingsRoute,
  WmsStockInRoute: WmsStockInRoute,
  WmsStockOutRoute: WmsStockOutRoute,
  WmsStockTransferRoute: WmsStockTransferRoute,
  WmsVendorsRoute: WmsVendorsRoute,
  HiringIndexRoute: HiringIndexRoute,
  WmsIndexRoute: WmsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
